### ISSUE TITLE
deprecated run

### ISSUE THREAD

**Issue by titusnicolae** [GoogleCloudPlatform/storage-file-transfer-json-python#4]
`from oauth2client.tools import run as run_oauth2` gives me
ImportError: cannot import name run

https://github.com/GoogleCloudPlatform/storage-file-transfer-json-python/blob/master/chunked_transfer.py#L39

Seems that run is deprecated in 1.5
https://github.com/insanum/gcalcli/issues/204

**Comment by porterjames** [comment]
I had the same issue. Workaround was to run pip install oauth2client==1.4.12 to downgrade oauth2client.

**Comment by jcriner** [comment]
This is fixed by the resolution of #5, and should be marked "closed."
