### ISSUE TITLE
Why not use Inbuilt retry and back off 

### ISSUE THREAD

**Issue by atibdialpad** [GoogleCloudPlatform/storage-file-transfer-json-python#9]
Rather than calling 'next_chunk' [here](https://github.com/GoogleCloudPlatform/storage-file-transfer-json-python/blob/594bc82120de6b684b9b7c234578ffa10b406105/chunked_transfer.py#L145) why not call 'execute'. For resumable type upload the client lib will take care of a) calling next_chunk until the chunked upload is done b) retrying for retryable errors with exponential backoff c) returning for non retryable errors. For non retryable errros, we can just retry the upload from scratch as mentioned [here](https://github.com/googleapis/google-api-python-client/blob/main/docs/media.md#resumable-media-chunked-upload)

@mco-gh @tswast @tmatsuo

**Comment by tswast** [comment]
@atibdialpad This sample is not using our recommended libraries and is planned to be archived (https://github.com/GoogleCloudPlatform/storage-file-transfer-json-python/issues/8).

That said, retries in Google Cloud Storage can be somewhat subtle to implement correctly. There is a library at https://github.com/googleapis/google-resumable-media-python which implements it with our latest best practices. I also recommend checking out the Google Cloud Storage client library at https://github.com/googleapis/python-storage
